### ISSUE TITLE
troubles running Nemoh on linux

### ISSUE THREAD

**Issue by elieso** [LHEEA/Nemoh#1]
Hi all, 
I downloaded Nemoh from the LHEEA website. 
I am trying to run it from a Linux OS. 
First I tried to use the makefile but there is an issue in the mesh.f90 file : 
" **>> USE MIdentification
>> Fatal Error : can't open module file 'midentification.mod' for reading at (1) : no such file or directory**"

Do you have any idea how I can fix this ?

thanks !

**Comment by mancellin** [comment]
Hi elieso,

On Nemoh user forum (http://lheea.ec-nantes.fr/redmine/projects/nemoh), another compilation problem has been reported several times recently: it seems to be due to a mix-up in the branches of the mercurial/git repository.
I'd suggest that you check if you have the right branch. Stable version is 2.03 and the source code can be found here: http://130.66.47.2/cgi-bin/hgweb.cgi/nemoh/archive/Nemoh_v2_03.tar.bz2

**Comment by elieso** [comment]
yes indeed I had the wrong version. The compilation works fine now. Thank you very much !
Another trouble though : I created an account to the Redmine forum but never received the activation email. 
Is there any way to fix this ?

**Comment by mancellin** [comment]
Please take a look at the "Contact us" box on
https://lheea.ec-nantes.fr/logiciels-et-brevets/nemoh-presentation-192863.kjsp

**Comment by gducrozet** [comment]
Problem solved.

By the way, Redmine is not active anymore and GitHub will be replaced soon by Gitlab for the 'official' repository of Nemoh (new features to come!!)
