### ISSUE TITLE
Problem in pitch results

### ISSUE THREAD

**Issue by ucar398** [LHEEA/Nemoh#9]
Hello all,

I have investigated the results of NEMOH (and HAMS) compared to WAMIT by OC3 Hywind Spar and OC4 DeepCWind semisubmersible. My overall results are quite good; however, I obtain irrelevant results in the pitch axis for both of the cases. I could not be able to access the NEMOH forum or find any guide. 

I have attached the comparison, and here is my study:
https://www.researchgate.net/publication/356129613_Comparison_and_Evaluation_of_Open-Source_Panel_Method_Codes_against_Commercial_Codes

I am in search of a guide
Thanks in advance,

OC3 Hywind:
![OC3 Hywind Spar](https://user-images.githubusercontent.com/75606804/143879475-255bbfdc-d02e-47ad-93a2-38bb516b37e4.PNG)

OC4 DeepCWind:
![OC4 DeepCWind Semisubmersible](https://user-images.githubusercontent.com/75606804/143879481-5ff40eac-b301-4e8c-8a7a-eb9a705aad56.PNG)

**Comment by ruddykurnia** [comment]
Hello,

Thank you very much for posting the issue.
The differences in the A55, B55, and Fe55  could be caused by the difference in position of the center of rotation/CoG. Could you please check the CoG input in Nemoh.cal? and how it is compared with the CoG input for the other software?

If that is not the case, could you please send me the input file, mesh file, and the NEMOH version for further investigation?

Kind regards,
Ruddy Kurnia

**Comment by ucar398** [comment]
Dr. Ruddy,

I have checked again, there is no error or mistake in CoG and rotation in any software. I have sent the files you wanted to your mail address: r.kurnia@labmath-indonesia.org

Regards,
Muhammed Uçar

**Comment by ruddykurnia** [comment]
Hi,

I have looked at your files. In your input for HAMS, ControleFile.in reference body center at (0,0,0) and also in Hydrostatic.in CoG (0,0,0). In your Nemoh.cal the reference point at (0,0,-89.9155). Please try to make the reference point the same, then you will get comparable results.

**Comment by ucar398** [comment]
Dear Ruddy,

It solved the problem. Thank you for your help.

Sincerely

Muhammed Ucar
Research Assistant

2 Ara 2021 Per, saat 11:37 tarihinde Ruddy Kurnia ***@***.***>
şunu yazdı:
